Search.appendIndex(
    [
                {
            "fqsen": "\\App\\DTO\\ProductOfferPriceDTO",
            "name": "ProductOfferPriceDTO",
            "summary": "Describes\u0020a\u0020special\u0020offer\u0020price",
            "url": "classes/App-DTO-ProductOfferPriceDTO.html"
        },                {
            "fqsen": "\\App\\DTO\\ProductOfferPriceDTO\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-DTO-ProductOfferPriceDTO.html#method___construct"
        },                {
            "fqsen": "\\App\\DTO\\ProductOfferPriceDTO\u003A\u003AgetQuantity\u0028\u0029",
            "name": "getQuantity",
            "summary": "",
            "url": "classes/App-DTO-ProductOfferPriceDTO.html#method_getQuantity"
        },                {
            "fqsen": "\\App\\DTO\\ProductOfferPriceDTO\u003A\u003A\u0024quantity",
            "name": "quantity",
            "summary": "",
            "url": "classes/App-DTO-ProductOfferPriceDTO.html#property_quantity"
        },                {
            "fqsen": "\\App\\DTO\\ProductPriceDTO",
            "name": "ProductPriceDTO",
            "summary": "Describes\u0020a\u0020product\u0020price",
            "url": "classes/App-DTO-ProductPriceDTO.html"
        },                {
            "fqsen": "\\App\\DTO\\ProductPriceDTO\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-DTO-ProductPriceDTO.html#method___construct"
        },                {
            "fqsen": "\\App\\DTO\\ProductPriceDTO\u003A\u003AgetPrice\u0028\u0029",
            "name": "getPrice",
            "summary": "",
            "url": "classes/App-DTO-ProductPriceDTO.html#method_getPrice"
        },                {
            "fqsen": "\\App\\DTO\\ProductPriceDTO\u003A\u003AgetProductCode\u0028\u0029",
            "name": "getProductCode",
            "summary": "",
            "url": "classes/App-DTO-ProductPriceDTO.html#method_getProductCode"
        },                {
            "fqsen": "\\App\\DTO\\ProductPriceDTO\u003A\u003A\u0024price",
            "name": "price",
            "summary": "",
            "url": "classes/App-DTO-ProductPriceDTO.html#property_price"
        },                {
            "fqsen": "\\App\\DTO\\ProductPriceDTO\u003A\u003A\u0024product_code",
            "name": "product_code",
            "summary": "",
            "url": "classes/App-DTO-ProductPriceDTO.html#property_product_code"
        },                {
            "fqsen": "\\App\\Exceptions\\CheckoutException",
            "name": "CheckoutException",
            "summary": "Exception\u0020class\u0020for\u0020Services\/Checkout",
            "url": "classes/App-Exceptions-CheckoutException.html"
        },                {
            "fqsen": "\\App\\Services\\Checkout\\PricingRules",
            "name": "PricingRules",
            "summary": "",
            "url": "classes/App-Services-Checkout-PricingRules.html"
        },                {
            "fqsen": "\\App\\Services\\Checkout\\PricingRules\u003A\u003AaddPrice\u0028\u0029",
            "name": "addPrice",
            "summary": "",
            "url": "classes/App-Services-Checkout-PricingRules.html#method_addPrice"
        },                {
            "fqsen": "\\App\\Services\\Checkout\\PricingRules\u003A\u003AaddOffer\u0028\u0029",
            "name": "addOffer",
            "summary": "",
            "url": "classes/App-Services-Checkout-PricingRules.html#method_addOffer"
        },                {
            "fqsen": "\\App\\Services\\Checkout\\PricingRules\u003A\u003AgetPrices\u0028\u0029",
            "name": "getPrices",
            "summary": "",
            "url": "classes/App-Services-Checkout-PricingRules.html#method_getPrices"
        },                {
            "fqsen": "\\App\\Services\\Checkout\\PricingRules\u003A\u003AgetOffers\u0028\u0029",
            "name": "getOffers",
            "summary": "",
            "url": "classes/App-Services-Checkout-PricingRules.html#method_getOffers"
        },                {
            "fqsen": "\\App\\Services\\Checkout\\PricingRules\u003A\u003AgetProductPrice\u0028\u0029",
            "name": "getProductPrice",
            "summary": "",
            "url": "classes/App-Services-Checkout-PricingRules.html#method_getProductPrice"
        },                {
            "fqsen": "\\App\\Services\\Checkout\\PricingRules\u003A\u003A\u0024prices",
            "name": "prices",
            "summary": "",
            "url": "classes/App-Services-Checkout-PricingRules.html#property_prices"
        },                {
            "fqsen": "\\App\\Services\\Checkout\\PricingRules\u003A\u003A\u0024offers",
            "name": "offers",
            "summary": "",
            "url": "classes/App-Services-Checkout-PricingRules.html#property_offers"
        },                {
            "fqsen": "\\App\\Services\\Checkout",
            "name": "Checkout",
            "summary": "Class\u0020used\u0020for\u0020Checkout\u0020and\u0020total\u0020price\u0020calculation",
            "url": "classes/App-Services-Checkout.html"
        },                {
            "fqsen": "\\App\\Services\\Checkout\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Services-Checkout.html#method___construct"
        },                {
            "fqsen": "\\App\\Services\\Checkout\u003A\u003Ascan\u0028\u0029",
            "name": "scan",
            "summary": "\u0022Scans\u0022\u0020and\u0020item\u0020by\u0020adding\u0020it\u0020to\u0020the\u0020internal\u0020\u0022basket\u0022\u0020and\u0020updates\u0020the\u0020total\u0020price",
            "url": "classes/App-Services-Checkout.html#method_scan"
        },                {
            "fqsen": "\\App\\Services\\Checkout\u003A\u003AaddProductsWithOffersToTotal\u0028\u0029",
            "name": "addProductsWithOffersToTotal",
            "summary": "Go\u0020through\u0020the\u0020special\u0020offers\u0020and\u0020the\u0020products\u0020with\u0020offers\u0020to\u0020the\u0020total\u0020price",
            "url": "classes/App-Services-Checkout.html#method_addProductsWithOffersToTotal"
        },                {
            "fqsen": "\\App\\Services\\Checkout\u003A\u003AaddProductsWithoutOffersToTotal\u0028\u0029",
            "name": "addProductsWithoutOffersToTotal",
            "summary": "Add\u0020products\u0020that\u0020don\u0027t\u0020have\u0020special\u0020offers\u0020to\u0020total\u0020price",
            "url": "classes/App-Services-Checkout.html#method_addProductsWithoutOffersToTotal"
        },                {
            "fqsen": "\\App\\Services\\Checkout\u003A\u003A\u0024pricing_rules",
            "name": "pricing_rules",
            "summary": "",
            "url": "classes/App-Services-Checkout.html#property_pricing_rules"
        },                {
            "fqsen": "\\App\\Services\\Checkout\u003A\u003A\u0024total",
            "name": "total",
            "summary": "Total\u0020basket\u0020price",
            "url": "classes/App-Services-Checkout.html#property_total"
        },                {
            "fqsen": "\\App\\Services\\Checkout\u003A\u003A\u0024basket",
            "name": "basket",
            "summary": "Internal\u0020basket\u0020items\u0020with\u0020quantities\u0020\u0028\u0020Product_code\u0020\u003D\u003E\u0020Quantity\u0020\u0029",
            "url": "classes/App-Services-Checkout.html#property_basket"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\DTO",
            "name": "DTO",
            "summary": "",
            "url": "namespaces/app-dto.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/app-exceptions.html"
        },                {
            "fqsen": "\\App\\Services\\Checkout",
            "name": "Checkout",
            "summary": "",
            "url": "namespaces/app-services-checkout.html"
        },                {
            "fqsen": "\\App\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/app-services.html"
        }            ]
);
